---
title: "Stats 20 Lesson 2"
author: "Damien Ha"
date: "6/25/2021"
output: html_document
---



#### Student ID Number: 905539967


# #1 


### Part A

``` {r perform_math}
9 / 3 + 7 * 5 * 6 + 16

24 / 3 * 4 - 3 + 7

10 - 4 + 7 + 3 * (24 / 4)

7<11

11>7

7<=11

11>=7

420 == 420

7!=11
```

### Part B

```{r perform_more_math}
sqrt(16) / 2^3


### The original expression was (2 * sin(30 degrees)) + (3 * cos(60 degrees)) - (3 * tan(45 degrees)) but trig functions in R use radians. 30 degrees is pi/6 radians, 60 degrees is pi/3 radians, and 45 degrees is pi/4 radians

(2 * sin(pi/6)) + (3 * cos(pi/3)) - (3 * tan(pi/4))


### The given equation is 51 = abs(5-4b), and the expressions in the vector below will solve for b

c(((51-5) / -4), ((-51-5) / -4))

```


# #2


### Part A

```{r create_objects}
`an_object` <- 1
an_object

`object number two` <- 1:2
`object number two`

`3rd_Object` <- 1:3
`3rd_Object`

`Third_Object` <- 1:4
Third_Object

`third_object` <- 1:5
third_object

`Final_object?` <- 1:6
`Final_object?`
```

# #3


### Part A

``` {r numerical_vectors}
c(6, 9, 4, 2, 0, 10, 7, 8, 5, 3)


vector2 <- c(1:500)


head(vector2)


vector3 <- seq(2, 1000, 2)


head(vector3)


cr_lynx <- c(lynx^(1/3))
cr_lynx
```


### Part B


``` {r character_vectors}
c("Ha", "Damien", "UCLA")


c(letters[rep(seq(1, 26, 1), each = 3)], letters[rep(seq(1, 7, 1), each = 3)])
```


### Part C


```{r logical_vectors}
logical_vector1 <- rep_len(c(T, F, F), 100)
logical_vector1

(logical_vector1)^2 
logical_vector2 <- (logical_vector1)^2 
logical_vector2 - 2
### When math is applied to a logical vector, R converts the logicals to numbers, so TRUEs become 1s and FALSEs become 0s. Then the math is applied to the resulting 1s and 0s

```



# #4

### Part A


```{r more_logical_vectors}
logical_vector1 <- rep_len(c(T, F, F), 100)
logical_vector2 <- (logical_vector1)^2 
logical_vector3 <- log(logical_vector2)
logical_vector3
### The natural log of the 1s was solved as 0, and the natural log of the 0s was solved as "-Inf" or negative infinity

```


```{r more_logical_vectors2}
1/0
### The result of this expression is "Inf" meaning infinity

```



# #5

### Part A


```{r help}

help(log)

help(exp)

help(sin)

help(cos)

help(tan)

help(asin)

help(acos)

help(atan)

help("%*%")

```


